// <auto-generated />
using System;
using CambridgeExamSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CambridgeExamSystem.Infrastructure.Migrations
{
    [DbContext(typeof(CambridgeDbContext))]
    [Migration("20261002083447_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.Achievement", b =>
                {
                    b.Property<int>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AchievementId"));

                    b.Property<string>("AchievementCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AchievementName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BadgeColor")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("RequiredScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("RequiredTests")
                        .HasColumnType("int");

                    b.Property<int>("RewardStars")
                        .HasColumnType("int");

                    b.HasKey("AchievementId");

                    b.HasIndex("AchievementCode")
                        .IsUnique();

                    b.ToTable("Achievements", (string)null);
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.AnswerOption", b =>
                {
                    b.Property<int>("QuestionOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionOptionId"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("MatchingKey")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("OptionCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("OptionOrder")
                        .HasColumnType("int");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("QuestionOptionId");

                    b.HasIndex("QuestionId", "OptionOrder")
                        .IsUnique();

                    b.ToTable("QuestionOptions", (string)null);
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.AttemptEvent", b =>
                {
                    b.Property<long>("AttemptEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AttemptEventId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("EventDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("ExamAttemptId")
                        .HasColumnType("bigint");

                    b.HasKey("AttemptEventId");

                    b.HasIndex("ExamAttemptId");

                    b.ToTable("AttemptEvents", (string)null);
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.AttemptResult", b =>
                {
                    b.Property<long>("AttemptResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AttemptResultId"));

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<long>("ExamAttemptId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("GradedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PercentageScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ResultMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("StarsEarned")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UnansweredCount")
                        .HasColumnType("int");

                    b.Property<int>("WrongCount")
                        .HasColumnType("int");

                    b.HasKey("AttemptResultId");

                    b.HasIndex("ExamAttemptId")
                        .IsUnique();

                    b.ToTable("AttemptResults", null, t =>
                        {
                            t.HasCheckConstraint("CK_AttemptResults_Percentage", "[PercentageScore] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.ExamLevel", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LevelCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LevelId");

                    b.HasIndex("LevelCode")
                        .IsUnique();

                    b.ToTable("ExamLevels", (string)null);
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.ExamPaper", b =>
                {
                    b.Property<int>("ExamPaperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamPaperId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ExamCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PassPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TotalScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("ExamPaperId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ExamCode")
                        .IsUnique();

                    b.HasIndex("LevelId", "IsPublished", "IsActive")
                        .HasDatabaseName("IX_ExamPapers_Level_Published");

                    b.ToTable("ExamPapers", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExamPapers_Duration", "[DurationMinutes] > 0");

                            t.HasCheckConstraint("CK_ExamPapers_TotalScore", "[TotalScore] >= 0");
                        });
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.Explanation", b =>
                {
                    b.Property<int>("ExplanationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExplanationId"));

                    b.Property<string>("ExplanationMediaUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ExplanationText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExplanationTitle")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("GrammarNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("TranscriptText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VocabularyNote")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExplanationId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionExplanations", (string)null);
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.LeaderboardSnapshot", b =>
                {
                    b.Property<long>("LeaderboardSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LeaderboardSnapshotId"));

                    b.Property<decimal>("AverageScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("LevelId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PeriodEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStartDate")
                        .HasColumnType("date");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("RankNumber")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<int>("TotalTests")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LeaderboardSnapshotId");

                    b.HasIndex("LevelId");

                    b.HasIndex("UserId");

                    b.HasIndex("PeriodType", "PeriodStartDate", "LevelId", "RankNumber")
                        .HasDatabaseName("IX_Leaderboard_Period");

                    b.ToTable("LeaderboardSnapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_LeaderboardSnapshots_PeriodType", "[PeriodType] IN ('Weekly', 'Monthly', 'AllTime')");
                        });
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.MotivationalMessage", b =>
                {
                    b.Property<int>("MotivationalMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MotivationalMessageId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal?>("MinPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("MotivationalMessageId");

                    b.ToTable("MotivationalMessages", (string)null);
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("CorrectTextAnswer")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DifficultyCode")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("ExamSectionId")
                        .HasColumnType("int");

                    b.Property<string>("InstructionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("QuestionGroupId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionOrder")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("QuestionId");

                    b.HasIndex("QuestionGroupId");

                    b.HasIndex("QuestionTypeId");

                    b.HasIndex("ExamSectionId", "QuestionOrder")
                        .IsUnique()
                        .HasDatabaseName("IX_Questions_Section_Order");

                    b.ToTable("Questions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Questions_Score", "[Score] >= 0");
                        });
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.QuestionGroup", b =>
                {
                    b.Property<int>("QuestionGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionGroupId"));

                    b.Property<int>("ExamSectionId")
                        .HasColumnType("int");

                    b.Property<int>("GroupOrder")
                        .HasColumnType("int");

                    b.Property<string>("GroupTitle")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PassageText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionGroupId");

                    b.HasIndex("ExamSectionId", "GroupOrder")
                        .IsUnique();

                    b.ToTable("QuestionGroups", (string)null);
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.QuestionMedia", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaId"));

                    b.Property<string>("AltText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("QuestionGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("MediaId");

                    b.HasIndex("QuestionGroupId");

                    b.HasIndex("QuestionId", "DisplayOrder")
                        .HasDatabaseName("IX_QuestionMedia_Question");

                    b.ToTable("QuestionMedia", null, t =>
                        {
                            t.HasCheckConstraint("CK_QuestionMedia_Owner", "[QuestionId] IS NOT NULL OR [QuestionGroupId] IS NOT NULL");

                            t.HasCheckConstraint("CK_QuestionMedia_Type", "[MediaType] IN ('Image', 'Audio', 'Video', 'Document')");
                        });
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.QuestionType", b =>
                {
                    b.Property<int>("QuestionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionTypeId"));

                    b.Property<bool>("AllowsTextAnswer")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresOptions")
                        .HasColumnType("bit");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("QuestionTypeId");

                    b.HasIndex("TypeCode")
                        .IsUnique();

                    b.ToTable("QuestionTypes", (string)null);
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.Section", b =>
                {
                    b.Property<int>("ExamSectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamSectionId"));

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("ExamPaperId")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SectionCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("SectionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SectionOrder")
                        .HasColumnType("int");

                    b.HasKey("ExamSectionId");

                    b.HasIndex("ExamPaperId", "SectionCode")
                        .IsUnique();

                    b.HasIndex("ExamPaperId", "SectionOrder")
                        .IsUnique();

                    b.ToTable("ExamSections", (string)null);
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.StarTransaction", b =>
                {
                    b.Property<long>("StarTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StarTransactionId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("ExamAttemptId")
                        .HasColumnType("bigint");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StarTransactionId");

                    b.HasIndex("ExamAttemptId");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_StarTransactions_User_Date");

                    b.ToTable("StarTransactions", (string)null);
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.TestAnswer", b =>
                {
                    b.Property<long>("AttemptAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AttemptAnswerId"));

                    b.Property<string>("AnswerJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ExamAttemptId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAnswered")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SavedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal?>("ScoreEarned")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("SelectedOptionId")
                        .HasColumnType("int");

                    b.Property<string>("TextAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeSpentSeconds")
                        .HasColumnType("int");

                    b.HasKey("AttemptAnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedOptionId");

                    b.HasIndex("ExamAttemptId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_AttemptAnswers_AttemptQuestion");

                    b.ToTable("AttemptAnswers", (string)null);
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.TestAttempt", b =>
                {
                    b.Property<long>("ExamAttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ExamAttemptId"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<int?>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentQuestionIndex")
                        .HasColumnType("int");

                    b.Property<int>("ExamPaperId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSubmitted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastSavedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal?>("MaxScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PercentageScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("StartedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<decimal?>("TotalScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TotalSecondsUsed")
                        .HasColumnType("int");

                    b.Property<int?>("UnansweredCount")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WrongCount")
                        .HasColumnType("int");

                    b.HasKey("ExamAttemptId");

                    b.HasIndex("CurrentQuestionId");

                    b.HasIndex("ExamPaperId");

                    b.HasIndex("UserId", "ExamPaperId", "StartedAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_ExamAttempts_User_Exam");

                    b.HasIndex("UserId", "Status", "LastSavedAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_ExamAttempts_User_Status");

                    b.ToTable("ExamAttempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExamAttempts_Score", "[TotalScore] IS NULL OR [TotalScore] >= 0");

                            t.HasCheckConstraint("CK_ExamAttempts_Status", "[Status] IN ('InProgress', 'Paused', 'Submitted', 'Expired', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CurrentLevelCode")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex")
                        .HasFilter("[NormalizedEmail] IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.UserAchievement", b =>
                {
                    b.Property<long>("UserAchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserAchievementId"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EarnedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserAchievementId");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId", "AchievementId")
                        .IsUnique();

                    b.ToTable("UserAchievements", (string)null);
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.UserStatistic", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("AverageScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("BestPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("CurrentRankCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Bronze");

                    b.Property<int>("CurrentStreakDays")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("LastActivityDate")
                        .HasColumnType("date");

                    b.Property<int>("LongestStreakDays")
                        .HasColumnType("int");

                    b.Property<int>("PassedTests")
                        .HasColumnType("int");

                    b.Property<long>("TotalLearningSeconds")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalStars")
                        .HasColumnType("int");

                    b.Property<int>("TotalTests")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("UserId");

                    b.ToTable("UserStatistics", (string)null);
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.UserVocabulary", b =>
                {
                    b.Property<long>("UserVocabularyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserVocabularyId"));

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DefinitionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExampleText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<bool>("IsBookmarked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastViewedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Phonetic")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TranslatedText")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserVocabularyId");

                    b.HasIndex("UserId", "OriginalText")
                        .IsUnique();

                    b.ToTable("UserVocabulary", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.AnswerOption", b =>
                {
                    b.HasOne("CambridgeExamSystem.Domain.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.AttemptEvent", b =>
                {
                    b.HasOne("CambridgeExamSystem.Domain.Entities.TestAttempt", "TestAttempt")
                        .WithMany("Events")
                        .HasForeignKey("ExamAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestAttempt");
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.AttemptResult", b =>
                {
                    b.HasOne("CambridgeExamSystem.Domain.Entities.TestAttempt", "TestAttempt")
                        .WithOne("Result")
                        .HasForeignKey("CambridgeExamSystem.Domain.Entities.AttemptResult", "ExamAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestAttempt");
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.ExamPaper", b =>
                {
                    b.HasOne("CambridgeExamSystem.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CambridgeExamSystem.Domain.Entities.ExamLevel", "Level")
                        .WithMany("ExamPapers")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.Explanation", b =>
                {
                    b.HasOne("CambridgeExamSystem.Domain.Entities.Question", "Question")
                        .WithMany("Explanations")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.LeaderboardSnapshot", b =>
                {
                    b.HasOne("CambridgeExamSystem.Domain.Entities.ExamLevel", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CambridgeExamSystem.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.Question", b =>
                {
                    b.HasOne("CambridgeExamSystem.Domain.Entities.Section", "Section")
                        .WithMany("Questions")
                        .HasForeignKey("ExamSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CambridgeExamSystem.Domain.Entities.QuestionGroup", "QuestionGroup")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CambridgeExamSystem.Domain.Entities.QuestionType", "QuestionType")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QuestionGroup");

                    b.Navigation("QuestionType");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.QuestionGroup", b =>
                {
                    b.HasOne("CambridgeExamSystem.Domain.Entities.Section", "Section")
                        .WithMany("QuestionGroups")
                        .HasForeignKey("ExamSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.QuestionMedia", b =>
                {
                    b.HasOne("CambridgeExamSystem.Domain.Entities.QuestionGroup", "QuestionGroup")
                        .WithMany("Media")
                        .HasForeignKey("QuestionGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CambridgeExamSystem.Domain.Entities.Question", "Question")
                        .WithMany("Media")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Question");

                    b.Navigation("QuestionGroup");
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.Section", b =>
                {
                    b.HasOne("CambridgeExamSystem.Domain.Entities.ExamPaper", "ExamPaper")
                        .WithMany("Sections")
                        .HasForeignKey("ExamPaperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamPaper");
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.StarTransaction", b =>
                {
                    b.HasOne("CambridgeExamSystem.Domain.Entities.TestAttempt", "TestAttempt")
                        .WithMany("StarTransactions")
                        .HasForeignKey("ExamAttemptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CambridgeExamSystem.Domain.Entities.User", "User")
                        .WithMany("StarTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TestAttempt");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.TestAnswer", b =>
                {
                    b.HasOne("CambridgeExamSystem.Domain.Entities.TestAttempt", "TestAttempt")
                        .WithMany("Answers")
                        .HasForeignKey("ExamAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CambridgeExamSystem.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CambridgeExamSystem.Domain.Entities.AnswerOption", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Question");

                    b.Navigation("SelectedOption");

                    b.Navigation("TestAttempt");
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.TestAttempt", b =>
                {
                    b.HasOne("CambridgeExamSystem.Domain.Entities.Question", "CurrentQuestion")
                        .WithMany()
                        .HasForeignKey("CurrentQuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CambridgeExamSystem.Domain.Entities.ExamPaper", "ExamPaper")
                        .WithMany("TestAttempts")
                        .HasForeignKey("ExamPaperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CambridgeExamSystem.Domain.Entities.User", "User")
                        .WithMany("TestAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentQuestion");

                    b.Navigation("ExamPaper");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.UserAchievement", b =>
                {
                    b.HasOne("CambridgeExamSystem.Domain.Entities.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CambridgeExamSystem.Domain.Entities.User", "User")
                        .WithMany("Achievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.UserStatistic", b =>
                {
                    b.HasOne("CambridgeExamSystem.Domain.Entities.User", "User")
                        .WithOne("Statistics")
                        .HasForeignKey("CambridgeExamSystem.Domain.Entities.UserStatistic", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.UserVocabulary", b =>
                {
                    b.HasOne("CambridgeExamSystem.Domain.Entities.User", "User")
                        .WithMany("Vocabulary")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("CambridgeExamSystem.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("CambridgeExamSystem.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("CambridgeExamSystem.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("CambridgeExamSystem.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CambridgeExamSystem.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("CambridgeExamSystem.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.ExamLevel", b =>
                {
                    b.Navigation("ExamPapers");
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.ExamPaper", b =>
                {
                    b.Navigation("Sections");

                    b.Navigation("TestAttempts");
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.Question", b =>
                {
                    b.Navigation("Explanations");

                    b.Navigation("Media");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.QuestionGroup", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.QuestionType", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.Section", b =>
                {
                    b.Navigation("QuestionGroups");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.TestAttempt", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Events");

                    b.Navigation("Result");

                    b.Navigation("StarTransactions");
                });

            modelBuilder.Entity("CambridgeExamSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("StarTransactions");

                    b.Navigation("Statistics");

                    b.Navigation("TestAttempts");

                    b.Navigation("Vocabulary");
                });
#pragma warning restore 612, 618
        }
    }
}
